api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from api import views


# Routers for the API
router = routers.DefaultRouter()
router.register(r'^manuscripts', views.ManuscriptViewSet)
router.register(r'^texts', views.TextViewSet)
router.register(r'^content', views.ManuscriptContentViewSet)


app_name = 'api'
urlpatterns = [
    url(r'^', include(router.urls)),
    # url('^manuscripts/(?P<pk>[0-9]+)/$', views.ManuscriptDetailView.as_view(), name='manuscript-detail')
    # url('^manuscript/(?P<manuscript_id>[0-9]+)/$', views.manuscript_json, name='manuscript-detail')
]

catalogue/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^manuscripts/', include('manuscripts.urls')),
    url('^commentaries/', include('commentaries.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^static/(?P<path>.*)$', views.serve),
    url(r'^api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commentaries/urls.py
from django.conf.urls import url

from . import views

app_name = 'commentaries'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.Details.as_view(), name='detail'),
    url(r'^inspected/$', views.Inspected.as_view(), name='inspected'),
    url(r'^relevant/$', views.Relevant.as_view(), name='relevant'),
    url(r'^projectfile/(?P<pk>[0-9]+)/$', views.ProjectFile.as_view(content_type='text/plain'), name='projectfile'),
]

manuscripts/urls.py
from django.conf.urls import url

from . import views

app_name = 'manuscripts'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url('^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail')
]

commentaries/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.forms import ValidationError
from catalogue.shared.functions import set_saeculo, truncate, attachment_id_path
from catalogue.shared.models import BaseModel
from persons.models import Commentator, Authority, Translator
import re

class Text(BaseModel):
    AUTHORSHIP = [
        ('certain', 'Certain'),
        ('possible', 'Possible'),
        ('disputed', 'Disputed'),
        ('dubious', 'Dubious'),
        ('untrue', 'Untrue'),
    ]
    RELEVANCE_HIGH = 1
    RELEVANCE_MID = 2
    RELEVANCE_LOW = 3
    RELEVANCE_UNKNOWN = 4
    RELEVANCE_NONE = 5
    RELEVANCE_CHOICES = (
        (RELEVANCE_HIGH, 'High'),
        (RELEVANCE_MID, 'Some'),
        (RELEVANCE_LOW, 'Low'),
        (RELEVANCE_UNKNOWN, 'Unknown'),
        (RELEVANCE_NONE, 'None'),
    )
    COVERAGE_NONE = 0
    COVERAGE_PARTIAL = 1
    COVERAGE_COMPLETE = 2
    COVERAGE_EARLY = 3
    EDITION_COVERAGE = (
        (COVERAGE_NONE, 'None'),
        (COVERAGE_PARTIAL, 'Partial'),
        (COVERAGE_COMPLETE, 'Full'),
        (COVERAGE_EARLY, 'Early print'),
    )
    TEXT_AUTHORITY = 1
    TEXT_COMMENTARY = 2
    TEXT_CHOICES = (
        (1, 'Authority text'),
        (2, 'Commentary'),
        (3, 'Summa or tractatus'),
        (4, 'Compilation or excerpts'),
    )

    title = models.CharField(max_length=500)
    title_addon = models.CharField('Title addon', max_length=255, blank=True, null=True)
    text_type = models.CharField(max_length=100, null=True, blank=True)
    date = models.CharField(max_length=50, null=True, blank=True)
    saeculo = models.CharField(max_length=50, null=True, blank=True)
    note = models.TextField(blank=True, null=True)
    literature = models.TextField(blank=True, null=True)
    author = models.ForeignKey(Commentator, blank=False)
    authorship = models.CharField(max_length=10, blank=True, null=True, choices=AUTHORSHIP)
    commentary_type = models.ForeignKey('CommentaryType', blank=True, null=True)
    commentary_on = models.ForeignKey('self', limit_choices_to=models.Q(text_type__contains=TEXT_AUTHORITY),
                                      blank=True, null=True)
    after = models.CharField('After date (earliest)', max_length=55, blank=True, null=True)
    before = models.CharField('Before date (latest)', max_length=55, blank=True, null=True)
    incipit = models.TextField(max_length=1020, blank=True, null=True)
    explicit = models.TextField(max_length=1020, blank=True, null=True)
    mora_reference = models.CharField(max_length=20, blank=True, null=True)
    relevance = models.IntegerField(blank=True, null=True, default=RELEVANCE_UNKNOWN, choices=RELEVANCE_CHOICES)
    related_commentaries = models.ManyToManyField('self', symmetrical=True, blank=True)
    edition_coverage = models.IntegerField(blank=True, default=COVERAGE_NONE, choices=EDITION_COVERAGE)

    class Meta:
        verbose_name = 'Text'
        verbose_name_plural = 'Texts'
        ordering = ['author', 'title', 'modified']

    def clean(self):
        if self.date and self.saeculo == '':
            self.saeculo = set_saeculo(self)
        mora_value = self.mora_reference
        if mora_value:
            reference_base = 'DA'
            regex_pattern = re.compile('([0-9]+)(.*?)$')
            if re.search(regex_pattern, mora_value):
                reference_number = re.search(regex_pattern, mora_value).group(1)
                reference_suffix = re.search(regex_pattern, mora_value).group(2)
            else:
                raise ValidationError("The Mora reference number must contain at least one digit.")

            if len(reference_number) > 3:
                raise ValidationError("The Mora reference number must not be longer than three digits.")
            if len(reference_number) == 3:
                self.mora_reference = reference_base + reference_number + reference_suffix
            elif len(reference_number) == 2:
                self.mora_reference = reference_base + '0' + reference_number + reference_suffix
            elif len(reference_number) == 1:
                self.mora_reference = reference_base + '00' + reference_number + reference_suffix

    def __str__(self):
        if self.title_addon:
            title_string = truncate(self.title + ' ({0})'.format(self.title_addon))
        else:
            title_string = truncate(self.title)
        return_string = '%s: %s' % (self.author, title_string)
        return truncate(return_string)


class CommentaryType(BaseModel):
    commentary_type = models.CharField(max_length=255)

    def __str__(self):
        return self.commentary_type


class Attachment(BaseModel):
    attachment = models.FileField(blank = True, upload_to = attachment_id_path)
    attached_to = models.ForeignKey('Text')

# class CommentaryEdition(BaseModel):
#     commentary = models.ForeignKey('Text')
#     edition = models.ForeignKey(TextEdition)
#     note = models.CharField(max_length=500, blank=True, null=True)

#     class Meta:
#         verbose_name_plural = 'Text editions'
#         verbose_name = 'Text edition'

#     def __str__(self):
#         return '%s: %s' % (self.edition, self.commentary)


class AuthorAlternative(BaseModel):
    author = models.ForeignKey(Commentator)
    commentary = models.ForeignKey('Text')
    note = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return 'Alternative: %s' % (self.author)

commentaries/forms.py
from django import forms
from commentaries.models import Text


class TextForm(forms.ModelForm):
    class Meta:
        model = Text
        fields = ['author', 'title', 'title_addon', 'text_type',
                  'commentary_type', 'commentary_on', 'authorship',
                  'date', 'saeculo', 'after', 'before', 'incipit',
                  'explicit', 'note', 'literature', 'edition_coverage',
                  'mora_reference', 'relevance', 'related_commentaries']
        widgets = {
            'incipit': forms.Textarea(attrs={'rows': 2, 'cols': 40}),
            'explicit': forms.Textarea(attrs={'rows': 2, 'cols': 40}),
        }

    text_type = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        choices=Text.TEXT_CHOICES)

commentaries/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Text
from manuscripts.models import ManuscriptContentCommentary, ManuscriptInspection, Manuscript


class IndexView(generic.ListView):
    template_name = 'texts/index.html'
    context_object_name = 'text_list'

    def get_queryset(self):
        """Return all text objects.
        """
        return Text.objects.all()


class Details(generic.DetailView):
    model = Text
    template_name = 'texts/detail.html'
    context_object_name = 'text_detail'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(Details, self).get_context_data(**kwargs)
        # Add a QuerySet of text witnesses
        context['witnesses'] = ManuscriptContentCommentary.objects.all()
        return context


class Inspected(generic.ListView):
    model = Text
    template_name = 'texts/inspections.html'
    context_object_name = 'texts'

    def get_queryset(self):
        # First, get all the inspected manuscripts
        inspection_ids = [inspection.manuscript.id for inspection in ManuscriptInspection.objects.all()]
        # Then, read all texts (on De anima) into memory
        all_texts = Text.objects.select_related().filter(commentary_on=148)
        # Find the content that has been inspected
        inspected_list = []
        for item in ManuscriptContentCommentary.objects.select_related().all():
            if item.manuscript.id in inspection_ids:
                inspected_list.append(item.content.id)

        # Sort the list of relevant texts into relevance lists
        text_list = {}
        text_list['high_relevance'] = []
        text_list['some_relevance'] = []
        text_list['low_relevance']  = []
        text_list['no_relevance']   = []
        text_list['unknown'] = []
        for text in all_texts:
            if text.id in inspected_list:
                if text.relevance == Text.RELEVANCE_HIGH:
                    text_list['high_relevance'].append(text)
                elif text.relevance == Text.RELEVANCE_MID:
                    text_list['some_relevance'].append(text)
                elif text.relevance == Text.RELEVANCE_LOW:
                    text_list['low_relevance'].append(text)
                elif text.relevance == Text.RELEVANCE_NONE:
                    text_list['no_relevance'].append(text)
                elif text.relevance == Text.RELEVANCE_UNKNOWN:
                    text_list['unknown'].append(text)
        text_list['total_count'] = len(
            text_list['high_relevance'] +
            text_list['some_relevance'] +
            text_list['low_relevance']  +
            text_list['no_relevance']   +
            text_list['unknown']
        )
        return(text_list)

class Relevant(generic.ListView):
    model = Text
    template_name = 'texts/relevant.html'
    context_object_name = 'texts'


    def get_queryset(self):
        # Read all texts (on De anima) into memory
        all_texts = Text.objects.select_related().filter(commentary_on=148)

        # Sort the list of relevant texts into relevance lists
        text_list = {}
        text_list['high_relevance'] = []
        text_list['some_relevance'] = []
        text_list['low_relevance']  = []
        text_list['no_relevance']   = []
        text_list['unknown'] = []
        for text in all_texts:
            if text.relevance == Text.RELEVANCE_HIGH:
                text_list['high_relevance'].append(text)
            elif text.relevance == Text.RELEVANCE_MID:
                text_list['some_relevance'].append(text)
            elif text.relevance == Text.RELEVANCE_LOW:
                text_list['low_relevance'].append(text)
            elif text.relevance == Text.RELEVANCE_NONE:
                text_list['no_relevance'].append(text)
            elif text.relevance == Text.RELEVANCE_UNKNOWN:
                text_list['unknown'].append(text)
        text_list['total_count'] = len(
            text_list['high_relevance'] +
            text_list['some_relevance'] +
            text_list['low_relevance']  +
            text_list['no_relevance']   +
            text_list['unknown']
        )
        return(text_list)

class ProjectFile(generic.DetailView):
    model = Text
    template_name = 'texts/project_file.html'
    context_object_name = 'text_detail'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ProjectFile, self).get_context_data(**kwargs)
        # Add a QuerySet of text witnesses
        context['witnesses'] = Manuscript.objects.select_related().filter(manuscriptcontentcommentary__content=kwargs['object'])
        return context

commentaries/templates/texts/detail.html
{% extends 'catalogue/base.html' %}

{% block content %}
<h1>{{ text_detail.author }}: {{ text_detail.title }}</h1>
<h2>Notes:</h2>
<p>{{ text_detail.note }}</p>

<h2>Witnesses</h2>
<ul>
  {% for item in witnesses %}
    {% if item.content.id == text_detail.id %}
      <li><a href="{% url 'manuscripts:detail' item.manuscript.id %}">{{ item.manuscript }}</a></li>
    {% endif %}
  {% endfor %}
</ul>
{{ texts }}

<h2>Project-file</h2>
<p>
    <a href="{% url 'commentaries:projectfile' text_detail.id %}">Create project file</a>
</p>
{% endblock %}

commentaries/templates/texts/index.html
{% extends 'catalogue/base.html' %}

{% block content %}
{% if text_list %}
    <ul>
    {% for com in text_list %}
    <li><a href="{% url 'commentaries:detail' com.id %}">{{ com.author }}, {{ com.title }}</a></li>
    <p>Note: {{ com.note }}</p>
    {% endfor %}
    </ul>
{% else %}
    <p>No comm. are available.</p>
{% endif %}
{% endblock %}

commentaries/templates/texts/inspections.html
{% extends 'catalogue/base.html' %}

{% block content %}
{% if texts %}
<h1>De anima commentaries inspected in manuscripts ({{ texts.total_count }})</h1>


<h2>High relevance ({{ texts.high_relevance|length }})</h2>

<div class="list-group">
    {% for text in texts.high_relevance %}
    <a href="{% url 'commentaries:detail' text.id %}" class="list-group-item">
        <h4 class="list-group-item-heading">
        {{ text }}
        </h4>
        {% if text.saeculo %}
        <p>
            Saeculo: {{ text.saeculo }}
        </p>
        {% endif %}
        <p>
            Edition coverage: {{ text.edition_coverage }}
        </p>
        <p>
            Note: {{ text.note|truncatechars:500 }}
        </p>
    </a>
    {% endfor %}
</div>

<h2>Some relevance ({{ texts.some_relevance|length }})</h2>
<ul>
  {% for text in texts.some_relevance %}
  <li><a href="{% url 'commentaries:detail' text.id %}">{{ text }}</a></li>
  {% endfor %}
</ul>

<h2>Low relevance ({{ texts.low_relevance|length }})</h2>
<ul>
  {% for text in texts.low_relevance %}
  <li><a href="{% url 'commentaries:detail' text.id %}">{{ text }}</a></li>
  {% endfor %}
</ul>

<h2>No relevance, but might have interesting content still... ({{ texts.no_relevance|length }})</h2>
<ul>
  {% for text in texts.no_relevance %}
  <li><a href="{% url 'commentaries:detail' text.id %}">{{ text }}</a></li>
  {% endfor %}
</ul>

<h2>Not evaluated... Yikes! ({{ texts.unknown|length }})</h2>
<ul>
  {% for text in texts.unknown %}
  <li><a href="{% url 'commentaries:detail' text.id %}">{{ text }}</a></li>
  {% endfor %}
</ul>


{% else %}
<p>No texts are available.</p>
{% endif %}
{% endblock %}

commentaries/templates/texts/project_file.html
<?xml version="1.0" encoding="UTF-8"?>
<listofFileNames>
    <header>
        <authorName>{{ text_detail.author }}</authorName>
        <commentaryName>{{ text_detail.title }}</commentaryName>
        <commentaryid></commentaryid>
        <commentaryslug>{{ text_detail.id }}</commentaryslug>
        <authorUri></authorUri>
  	    <parentUri></parentUri>
  	    <textfilesdir></textfilesdir>
        <webbase>null</webbase>
        <questionListSource></questionListSource>
        <questionListOriginalEditor>Michael Stenskjær Christensen</questionListOriginalEditor>
        <questionListEncoder>Michael Stenskjær Christensen</questionListEncoder>
  	    <!-- possible metadata should go here or be added elsewhere 
  	       -->
        <hasWitnesses>
            {% for item in witnesses %}
            <witness id="{{ item.library.library_town|make_list|slice:'1'|join:''|upper }}">
                <slug>{{ item.library.library_town|make_list|slice:'3'|join:''|lower }}{{ item.number|cut:' '|lower }}</slug>
                <title>{{ item }}</title>
                <initial>{{ item.library.library_town|make_list|slice:'1'|join:''|upper }}</initial>
            </witness>
           {% endfor %}
        </hasWitnesses>
    </header>
    <div id="body" xml:lang="la">
        <div id="{{ item.id }}-librum1">
            <head>
                Liber primus
            </head>
            <item id="{{ item.id }}-prooemium">
    	          <fileName filestem="{{ item.id }}-prooemium"/>
    	          <title>Prooemium</title>
    	          <questionTitle/>
    	          <hasWitnesses>
    		            <witness ref="...">
    			              <folio>...</folio>
    		            </witness>
                    <witness ref="...">
                        <folio>...</folio>
                    </witness>
    	          </hasWitnesses>
            </item>
            <item id="{{ item.id }}-l1q1" type="quaestio">
                <fileName filestem="{{ item.id }}-l1q1"/>
                <title>...</title>
                <hasWitnesses>
                    <witness ref="...">
                        <folio>...</folio>
                    </witness>
                </hasWitnesses>
            </item>
        </div>
	  </div>
</listofFileNames>

commentaries/templates/texts/relevant.html
{% extends 'catalogue/base.html' %}

{% block content %}
{% if texts %}
<h1>All De anima commentaries, sorted by relevance ({{ texts.total_count }})</h1>


<h2>High relevance ({{ texts.high_relevance|length }})</h2>

<div class="list-group">
    {% for text in texts.high_relevance %}
    <a href="{% url 'commentaries:detail' text.id %}" class="list-group-item">
        <h4 class="list-group-item-heading">
        {{ text }}
        </h4>
        {% if text.saeculo %}
        <p>
            Saeculo: {{ text.saeculo }}
        </p>
        {% endif %}
        <p>
            Edition coverage: {{ text.edition_coverage }}
        </p>
        <p>
            Note: {{ text.note|truncatechars:500 }}
        </p>
    </a>
    {% endfor %}
</div>

<h2>Some relevance ({{ texts.some_relevance|length }})</h2>
<ul>
  {% for text in texts.some_relevance %}
  <li><a href="{% url 'commentaries:detail' text.id %}">{{ text }}</a></li>
  {% endfor %}
</ul>

<h2>Low relevance ({{ texts.low_relevance|length }})</h2>
<ul>
  {% for text in texts.low_relevance %}
  <li><a href="{% url 'commentaries:detail' text.id %}">{{ text }}</a></li>
  {% endfor %}
</ul>

<h2>No relevance, but might have interesting content still... ({{ texts.no_relevance|length }})</h2>
<ul>
  {% for text in texts.no_relevance %}
  <li><a href="{% url 'commentaries:detail' text.id %}">{{ text }}</a></li>
  {% endfor %}
</ul>

<h2>Not evaluated... Yikes! ({{ texts.unknown|length }})</h2>
<ul>
  {% for text in texts.unknown %}
  <li><a href="{% url 'commentaries:detail' text.id %}">{{ text }}</a></li>
  {% endfor %}
</ul>


{% else %}
<p>No texts are available.</p>
{% endif %}
{% endblock %}